[russian]
before_off_message = """
Я буду отключён сейчас, меня улучшают или чинят, подождите, пожалуйста 😊
"""
can_not_lessons = """
*Произошла ошибка при поиске.*
Убедитесь что правильно ввели класс или ФИО.

Если вы уверены, что ввели все верно, и я должен найти расписание, но не нашёл, свяжитесь с разработчиками, использовав специальную кнопку во вкладке *Другое*
"""
canteen_timetable_header = """Расписание столовой для вашей школы:
"""
canteen_timetable_format = """ 
*{corpus_name}*

{canteen_text}
"""
certain_day_timetable = """
Уроки в {day_of_week}:
{lessons}
"""
change_me = """
Пожалуйста, выберите кто вы 😉
"""
check_your_info = """
Что-то пошло не так, проверьте правильность данных введенных при регистрации. Если они верные, а ошибка все равно возникает, свяжитесь с разработчиками, использовав специальную кнопку во вкладке *Другое*
"""
confirm_class = """
Ваш класс - *{subclass}*, верно?
"""
confirm_another_class = """
Вы ищите класс - *{subclass}*, верно?
"""
confirm_name = """
Ваше ФИО - *{teacher_name}*, верно?
"""
donate_message = """
*Сбер*:
`5469 3800 7830 2212`

*Тинькофф*:
`5536 9140 1979 1460`

*Юмани*:
`410017707536662`

Заранее огромное вам спасибо за любую копеечку, разработчики должны платить за сервер, а ещё хотят кушать, чтобы работать, так что всё идёт в дело!🤍
"""
enter_group = """
Выберите, пожалуйста, подгруппу:
"""
enter_letter = """
Выберите, пожалуйста, букву класса:
"""
enter_name = """
Пожалуйста, введите фамилию
"""
enter_school_name = """
Введите, пожалуйста номер или название школы"""
enter_parallel = """
Выберите параллель, пожалуйста:
"""
find_text = """
Выберите какое расписание вы хотите получить:
"""
greeting = """
Здравствуйте, я – ваш школьный ассистент, меня зовут _*Sкедуль*_ 🙂

Я создан для помощи, умею выдавать расписание для вас или другого класса/учителя, присылаю объявления и другое, мой функционал расширятся с вашей помощью, спасибо, что пишите свои идеи разработчикам 😊

Управлять мной легко, интерфейс прост и понятен, так что попробуйте, но сначала и я вас немного поспрашиваю 😉

Для начала я хочу узнать кто вы, выберите, пожалуйста 🙂


"""
help_message = """
Наши контакты:
@Dartt0n - технический директор (пишите о неточностях в расписании и багах)
@aaartamoshaaa - *самый общительный*, который постарается вас понять и возможно помочь (пишите обо всём другом: *идеи, предложения*)
@mrcatcis - невероятно ценный сотрудник (пишите о багах)
@SaveliyH - невероятно ценный сотрудник

При обращении в тех. поддержку сообщите эти данные:
`{telegram_id}`

 Мои *разработчики тоже люди* как и вы, они могут отвечать не сразу, будьте, пожалуйста, вежливы и терпеливы 🙂
"""
help_on_startup = """
Вы уже зарегистрированы, вы сейчас *в главном меню* 😉

Если есть какие-то проблемы, то попробуйте сначала нажать /start, если не помогло - напишите моим разработчикам, пожалуйста, в меню \"*другое*\" есть специальная кнопка для этого 🙂
"""
helpful_materials = """
Выберите, пожалуйста, нужный вам пункт:
"""
lesson_format = """
Урок №{lesson_number} {lesson_time}
Предмет: \"{subject}\"
{misc_info}
{cabinet}
"""
main_menu = """
Вы *в главном меню*, можете спрашивать меня о чём хотите с помощью кнопок, буду рад помочь 😉

Во вкладке \"Другое\" вы *можете узнать расписание звонков, столовой, изменить информацию о себе, обратиться к разработчикам, просмотреть последние объявления, и ссылки на полезные материалы.*
"""
main_menu_first = """
Итак, спасибо, я запомнил, теперь вы *в главном меню*, можете спрашивать меня о чём хотите с помощью представленного меню, кнопки подписаны, пробуйте, буду рад помочь 😉

Во вкладке *\"Другое меню\"* вы можете узнать расписание звонков, столовой, *изменить информацию о себе, обратиться к разработчикам*, просмотреть последние объявления.
"""
misc_menu = """
Это меню дополнительных возможностей, буду рад помочь 😉
"""
no_lessons = """
Нет уроков!
"""
no_lessons_today = """
Сегодня нет уроков! Приятного отдыха!
"""
restart_message = """
Я был перезагружен, нажмите, пожалуйста, на подсвеченный текст: /start 🙂
"""
rings_timetable_header = """
*РАСПИСАНИЕ ЗВОНКОВ*:
НОМЕР    ВРЕМЯ
"""
rings_timetable_format = """
{lesson_number:<16} {time:<20}
"""
save_student_class = """
Можете сообщить мне свой класс, чтобы я запомнил, и вам не пришлось указывать его в следующий раз, очень советую это сделать 😉
Согласны?
"""
save_teacher_name = """
Можете представиться мне по имени, чтобы я запомнил, и вам не пришлось его указывать в следующий раз, очень советую это сделать 😉
Согласны?
"""
select_day_of_week = """
Выберите день недели из предложенных, пожалуйста:
"""
select_school_name = """
Выберите, пожалуйста вашу школу из списка похожих и знакомых мне:
P.S. Если вашей школы нет в списке, то проверьте правильность написания или я не знаю о ней😪
*НО* это можно исправить, как - узнайтие тут http://skedule.tilda.ws/"""
today_timetable = """
Уроки сегодня:
{lessons}
"""
tomorrow_timetable = """
Уроки завтра:
{lessons}
"""
tutorials = """
Скоро тут будут ссылки на туториалы
"""
wanted_certain_day_timetable = """
Уроки {wanted} в {day_of_week}:
{lessons}
"""
wanted_today_timetable = """
Уроки {wanted} сегодня:
{lessons}
"""
wanted_tomorrow_timetable = """
Уроки {wanted} завтра:
{lessons}
"""
wrong_format_name = """
❌ Неверный формат.
Введите, пожалуйста, ФИО *как в примере*, с соблюдением формата - *Иванов И.И.*
"""
admin_main_menu = """
Вы *в главном меню*, можете спрашивать меня о чём хотите с помощью кнопок, буду рад помочь 😉

Во вкладке *\"Другое меню\"* вы можете узнать расписание звонков, столовой, *изменить информацию о себе, обратиться к разработчикам*, просмотреть последние объявления.
"""
parent_main_menu = """
Вы *в главном меню*, можете спрашивать меня о чём хотите с помощью кнопок, буду рад помочь 😉

Во вкладке *\"Другое меню\"* вы можете узнать расписание звонков, столовой, *изменить информацию о себе, обратиться к разработчикам*, просмотреть последние объявления.
"""
teacher_main_menu = """
Вы *в главном меню*, можете спрашивать меня о чём хотите с помощью кнопок, буду рад помочь 😉

Во вкладке *\"Другое меню\"* вы можете узнать расписание звонков, столовой, *изменить информацию о себе, обратиться к разработчикам*, просмотреть последние объявления.
"""
student_main_menu = """
Вы *в главном меню*, можете спрашивать меня о чём хотите с помощью кнопок, буду рад помочь 😉

Во вкладке *\"Другое меню\"* вы можете узнать расписание звонков, столовой, *изменить информацию о себе, обратиться к разработчикам*, просмотреть последние объявления.
"""
admin_misc_menu = """
Это меню дополнительных возможностей, буду рад помочь 😉
"""
parent_misc_menu = """
Это меню дополнительных возможностей, буду рад помочь 😉
"""
teacher_misc_menu = """
Это меню дополнительных возможностей, буду рад помочь 😉
"""
student_misc_menu = """
Это меню дополнительных возможностей, буду рад помочь 😉
"""
choose_children = """
Выберите, пожалуйста, ребёнка, расписание которого хотите посмотреть 🙂

"""
choose_role = """
Выберите, пожалуйста, вашу роль 🙂

"""
confirm_for_admin = """
Регестрируетесь как работник для школы {school_name}?
"""
select_teacher_from_list = """
Выберите, пожалуйста, учителя из списка похожих и знакомых мне:
"""
confirm_another_teacher = """
Вы ищите расписание для учителя {teacher_name}?
"""
children_information = """
какая-то инфа о ребёнке

"""
settings_menu = """
Это меню настроек, здесь вы можете изменить информацию о себе 😉

"""
successful_reg_admin = """
Вы успешно зарегистрированы как работник администрации школы {school_name} 😌

"""
successful_reg_teacher = """
*{teacher_name}*, вы успешно зарегистрированы как учитель 😌

"""
successful_reg_student = """
Вы успешно зарегистрированы как ученик *{subclass}* класса 😌

"""
successful_reg_parent = """
Вы успешно зарегистрированы как родитель 😌

"""
change_role = """
Вы на этапе смены роли
"""
