[russian]
before_off_message = """
Attention! Ремонтные работы. Это значит только одно - прямо сейчас мы улучшаем наш сервис для вас. Нам нужно мгновение! Спасибо за терпение :)
"""
can_not_lessons = """
Ой! Проблема - наш сервис не может ответить на ваш запрос. Пожалуйста, убедитесь, что вы правильно ввели класс или ФИО и попробуйте снова.
Если все введено верно, то, кажется, самое время связаться с разработчиками и сообщить о баге через кнопку "Другое". Спешим на помощь!
"""
canteen_timetable_header = """Расписание столовой для вашей школы:
"""


confirm_class = """
Ваш класс - *{subclass}*, верно?
"""

confirm_child_class = """
Класс вашего ребёнка - *{subclass}*, верно?
"""

not_enough_premium_children = """
Ой! К сожалению так пока нельзя сделать :(
"""

confirm_another_class = """
Вы ищите класс - *{subclass}*, верно?
"""

choose_delete_child = """
Пожалуйста, выберите ребёнка, которого вы хотите удалить:
"""

submit_delete_child = """
Вы уверены, что хотите удалить {child_name}?
"""

successful_delete_child = """
Вы успешно удалили {child_name}!
"""

successful_reg_child = """
Юху! Вы успешно добавили ребёнка {child_name}, тепперь сможете легко смотреть его расписание и многое другое 😉
"""

confirm_reg_parent = """
Запоминаю вас как родителя?
"""

confirm_name = """
Ваше ФИО - *{teacher_name}*, верно?
"""


donate_message = """
Спасибо вам за помощь в развитии нашего проекта :)
Бот работает для вас бесплатно, но есть ряд операционных расходов, которые мы берем на себя.

Сбер:
`5469 3800 7830 2212`

Тинькофф:
`5536 9140 1979 1460`

Юмани:
`410017707536662`

Вы помогаете нам развиваться, идти вперед и делать сервис лучше для вас 🤍
"""

enter_group = """
Вы выбрали: {parallel}{letter}
Выберите, пожалуйста, подгруппу:
"""
enter_letter = """
Вы выбрали: {parallel}
Выберите, пожалуйста, букву класса:
"""
enter_name_on_register = """
Вы выбрали школу: "{school_name}"

Пожалуйста, сообщите мне свою фамилию :) 

Я запомню эту информацию, в след.раз указывать ее не нужно будет указывать. А еще мы станем чуточку ближе!

Круто же?
"""

enter_name = """
Пожалуйста, введите фамилию учителя
"""

enter_child_name = """
Пожалуйста, введите имя и фамилию ребёнка, или то как вы его называете, чтобы вам было удобнее ориентироваться 🙂

P.S. То что вы введёте, будет видно только вам
"""

submit_child_name = """
Вы ввели такое имя - {child_name}, запоминаю?
"""

enter_school_name = """
Введите, пожалуйста номер или название школы
"""
enter_parallel = """
Выберите, пожалуйста, параллель из списка:
"""
enter_parallel_on_register_student = """
Вы выбрали школу: "{school_name}"

Пожалуйста, сообщите мне свой класс. Я запомню эту информацию, в следующий раз ее не нужно будет указывать.

Круто же?

Итак, выберите, пожалуйста, параллель из списка:
"""
enter_parallel_on_register_parent = """
Вы выбрали школу: "{school_name}"

Пожалуйста, сообщите мне класс своего ребёнка. Я запомню эту информацию, в следующий раз ее не нужно будет указывать.

Круто же?

Итак, выберите, пожалуйста, параллель из списка:
"""

child_menu = """
Сейчас вы смотрите расписание {child_name}
"""

greeting = """
Привет! 
Я - Sкeдуль, ваш школьный ассистент.

Помогаю ученикам, родителям и учителям не потеряться в огромном школьном расписании. 

Иногда я присылаю вам объявления, оперативно обновляю расписанию и, вообще, становлюсь лучше с каждым днем (благодаря вам!)

Со мной легко и просто. Но сначала познакомимся! 

Поехали?

Итак, выберите, пожалуйста, вашу роль.
"""
help_message = """
Кажется, у вас есть обратная связь или предложение. Мы открыты к диалогу и сотрудничеству.

Если у вас:
- что-то не работает/сломалось в боте,
- есть комментарии по улучшению некоторых функций или идеи, как дополнить функционал,

то смело пишите: 
@Dartt0n - Кудрявцев Антон, CTO проекта;
@mrcatcis - Доможиров Антон, программист бота, CI/CD Engineer
Возможно, мы попросим у вас это число: 
```{telegram_id}```

Если вы:
- хотите подключить систему Sкeдуль в вашу школу,
- предложить любое возможное партнерство,

то смело пишите:
@aaartamoshaaa - Хачатуров Артем, CEO проекта.

До связи!
"""

help_message_before_reg = """
Кажется, у вас есть обратная связь или предложение. Мы открыты к диалогу и сотрудничеству.

Если у вас:
- что-то не работает/сломалось в боте,
- есть комментарии по улучшению некоторых функций или идеи, как дополнить функционал,

то смело пишите: 
@Dartt0n - Кудрявцев Антон, CTO проекта;
@mrcatcis - Доможиров Антон, программист бота, CI/CD Engineer
Возможно, мы попросим у вас это число: 
```{telegram_id}```

Если вы:
- хотите подключить систему Sкeдуль в вашу школу,
- предложить любое возможное партнерство,

то смело пишите:
@aaartamoshaaa - Хачатуров Артем, CEO проекта.

Для завершения регистрации необходимо выбрать роль.
"""

rings_timetable_header = """
*РАСПИСАНИЕ ЗВОНКОВ*:
НОМЕР    ВРЕМЯ
"""
rings_timetable_format = """
{lesson_number:<16} {time:<20}
"""

select_day_of_week = """
Выберите день недели из предложенных, пожалуйста:
"""
select_school_name = """
Пожалуйста, выберите вашу школу из списка знакомых мне:
"""


student_main_menu = """
Вы в *"главном меню"* - самое время показать, что я могу :)
🔸Кнопки "найти класс" и "найти учителя" ищут расписание других людей, остальные кнопки выдают *ваше расписание.* 

Кстати, во вкладке "Другое", вы можете:
- узнать расписание звонков,
- расписание столовой,
- изменить информацию о себе (или вашу роль: ученик, учитель, родитель на другую)
- обратиться за помощью к разработчикам,
- посмотреть последние объявления,
- и даже найти ссылки на полезные материалы.
"""
teacher_main_menu = """
Вы в *"главном меню"* - самое время показать, что я могу :)
🔸Кнопки "найти класс" и "найти учителя" ищут расписание других людей, остальные кнопки выдают *ваше расписание.* 

Кстати, во вкладке "Другое", вы можете:
- узнать расписание звонков,
- расписание столовой,
- изменить информацию о себе (или вашу роль: ученик, учитель, родитель на другую)
- обратиться за помощью к разработчикам,
- посмотреть последние объявления,
- найти свободный сейчас кабинет.
"""

parent_main_menu = """
Вы в *"меню родителя"* - самое время показать, что я могу :)
Вы можете:
- изменить информацию о себе (или вашу роль: ученик, учитель, родитель на другую),
- обратиться за помощью к разработчикам или поддержать их,
- вернуться в главное меню и посмотреть расписание ребёнка там.
"""
admin_main_menu = """
Вы в *"главном меню"* - самое время показать, что я могу :)
🔸Кнопки "найти класс" и "найти учителя" ищут расписание других людей. 

Кстати, во вкладке "Другое", вы можете:
- узнать расписание звонков,
- расписание столовой,
- изменить информацию о себе (или вашу роль: ученик, учитель, родитель на другую)
- обратиться за помощью к разработчикам,
- посмотреть последние объявления,
- и даже найти ссылки на полезные материалы.
"""

admin_misc_menu = """
Это меню дополнительных возможностей, буду рад помочь 😉
"""
parent_misc_menu = """
Это меню дополнительных возможностей, буду рад помочь 😉
"""
teacher_misc_menu = """
Это меню дополнительных возможностей, буду рад помочь 😉
"""
student_misc_menu = """
Это меню дополнительных возможностей, буду рад помочь 😉
"""

choose_children = """
Выберите, пожалуйста, ребёнка, расписание которого хотите посмотреть 🙂

Здесь же вы можете:
- добавлять детей,
- удалять детей,
- перейти в *меню родителя*, и там связаться с разработчиками.

"""
choose_role = """
Выберите, пожалуйста, вашу роль 🙂

"""
confirm_for_admin = """
Регистрируетесь как работник для школы "{school_name}"?
"""
select_teacher_from_list = """
Выберите, пожалуйста, учителя из списка похожих и знакомых мне:
"""
confirm_another_teacher = """
Вы ищите расписание для учителя {teacher_name}?
"""

successful_reg_admin = """
Вы успешно зарегистрированы как работник администрации школы "{school_name}" 😌
Приятно познакомиться! 

Вы в *"главном меню"* - самое время показать, что я могу :)
🔸Кнопки "найти класс" и "найти учителя" ищут расписание других людей. 

Кстати, во вкладке "Другое", вы можете:
- узнать расписание звонков,
- расписание столовой,
- изменить информацию о себе (или вашу роль: ученик, учитель, родитель на другую)
- обратиться за помощью к разработчикам,
- посмотреть последние объявления,
- и даже найти ссылки на полезные материалы.
"""
successful_reg_teacher = """
*{teacher_name}*, вы успешно зарегистрированы как учитель 😌
Приятно познакомиться! 

Вы в *"главном меню"* - самое время показать, что я могу :)
🔸Кнопки "найти класс" и "найти учителя" ищут расписание других людей, остальные кнопки выдают *ваше расписание.* 

Кстати, во вкладке "Другое", вы можете:
- узнать расписание звонков,
- расписание столовой,
- изменить информацию о себе (или вашу роль: ученик, учитель, родитель на другую)
- обратиться за помощью к разработчикам,
- посмотреть последние объявления,
- найти свободный сейчас кабинет.
"""

successful_reg_student = """
Вы успешно зарегистрированы как ученик *{subclass}* класса 😌
Приятно познакомиться! 

Вы в *"главном меню"* - самое время показать, что я могу :)
🔸Кнопки "найти класс" и "найти учителя" ищут расписание других людей, остальные кнопки выдают *ваше расписание.* 

Кстати, во вкладке "Другое", вы можете:
- узнать расписание звонков,
- расписание столовой,
- изменить информацию о себе (или вашу роль: ученик, учитель, родитель на другую)
- обратиться за помощью к разработчикам,
- посмотреть последние объявления,
- и даже найти ссылки на полезные материалы.


"""
successful_reg_parent = """
Вы успешно зарегистрированы как родитель 😌
Приятно познакомиться! 

А теперь, давайте, добавим вашего ребёнка, это совсем не сложно, также ответьте на парочку моих вопросов и я запомню 😌

"""


announcements = """
Ваши объявления:

"""

free_cabinets = """
Свободные кабинеты на урок №{lesson_number} в {corpus_name}:

"""

no_current_lessons = """
Сейчас нет уроков, отдыхайте 😌
"""

no_free_cabinets = """
Я не нашёл свободных кабинетов :(
"""

free_cabinets_choose_corpuses = """
Выберите, пожалуйста, корпус, в котором хотите найти свободный кабинет.
"""
