# use this file to compile texts.py file
from src.config import TEXTS_PATH
from pathlib import Path
import toml

path = Path(__file__).parent / "texts.py"


texts = toml.load(TEXTS_PATH.open("r", encoding="utf-8"))["russian"]

with path.open("w", encoding="utf-8") as source_file:
    source_file.write(
        "# NOTE: this is autogenerated file\n"
        + "class Texts:\n"
        + "\n".join((f'    {field} = """{value}"""' for field, value in texts.items()))
    )
