from aiogram.dispatcher.filters.state import State, StatesGroup


class States(StatesGroup):
    student_menu = State()
    teacher_menu = State()
    administration_menu_first = State()
    administration_menu_second = State()

    add_more_childs = State()
    child_menu = State()
    find_menu = State()
    find_day_of_week = State()
    child_day_of_week = State()
    child_misc_menu_first = State()
    parent_misc_menu_first = State()
    student_submit = State()
    student_day_of_week = State()
    student_misc_menu_first = State()
    student_misc_menu_second = State()
    teacher_day_of_week = State()
    teacher_misc_menu_first = State()
    teacher_misc_menu_second = State()
    delete_role = State()
    teacher_submit = State()
    administration_submit = State()
    find_student_submit = State()
    find_enter_parallel = State()
    find_enter_letter = State()
    find_enter_group = State()
    find_teacher_submit = State()
    find_day_of_week = State()
    find_input_teacher = State()
    find_choose_teacher = State()

    choose_role = State()
    input_school = State()
    show_childs = State()
    choose_school = State()
    input_teacher = State()
    choose_teacher = State()
    teacher_submit = State()
    enter_parallel = State()
    enter_letter = State()
    enter_group = State()
    student_submit = State()

    misc_menu_second = State()

    teacher_free_cabinets_corpuses = State()
    administration_free_cabinets_corpuses = State()

    register_parent = State()
    enter_child_name = State()
    submit_child_name = State()
    submit_delete_child = State()
    choose_delete_child = State()

    show_free_cabinets = State()